

use_frameworks!

target 'Tomaa assignment 1 milestone 1' do
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'Tomaa assignment 1 milestone 1Tests' do
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
end